http:
  addr: 0.0.0.0:5556 # 服务监听地址
timeout: 30s # 服务端超时
jwt-key: 9NJE1L0b4Vf2UG8IitQgr0lw0odMu0y8 # jwt 签名密钥
expiration: 7 # token 过期时间，单位：天
postgresql:
  addr: 127.0.0.1:54321
  username: postgres
  password: postgres
  database: blog-v4
  max-idle-connections: 100 # 最大空闲连接数
  max-open-connections: 1000 # 最大打开连接数
  max-connection-life-time: 5m # 连接最大生命周期
  log-level: 4 # 日志级别
redis: # Redis 数据库相关配置
  addr: 127.0.0.1:56379 # Redis 服务器地址和端口，默认 127.0.0.1:6379
  username: ""# Redis 用户名（使用默认用户，留空）
  password: Q6jAu8trwDEcJN7V # Redis 用户密码
  database: 0 # Redis 数据库索引，默认 0
  max-retries: 3 # 最大重试次数，默认 3
  min-idle-conns: 0 # 最小空闲连接数，默认 0
  dial-timeout: 5s # 拨号超时时间，默认 5
  read-timeout: 3s # 读取超时时间，默认 3
  write-timeout: 3s # 写入超时时间，默认 3
  pool-time: 4s # 连接池超时时间，默认 4s
  pool-size: 10 # 连接池大小，默认 10
  enable-trace: false # 是否启用链路追踪，默认 false
otel:
  endpoint: 127.0.0.1:4327
  service-name: blog-apiserver
  output-mode: otel # 支持 otel、console、file、slog
  level: debug
  add-source: true
  use-prometheus-endpoint: true
  slog:
    # 改配置项只有 output-mod 为 slog 时生效
    format: text
    time-format: "2006-01-02 15:04:05"
    output: stdout # 支持 stdout, stderr, or file path
